project:
  type: website
  output-dir: .

website:
  title: ""

  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: cv.pdf
        text: CV

      - text: EPPS 6323
        menu:
          - href: assignment1.qmd
            text: Assignment 1
          - href: assignment2.qmd
            text: Assignment 2
          - href: assignment3.qmd
            text: Assignment 3
          - text: Labs
            menu:
              - href: Lab01.qmd
                text: Lab01
              - href: Lab02.qmd
                text: Lab02
        

      - text: EPPS 6354
        menu:
          - href: assignment4.qmd
            text: Assignment 4
          - href: assignment5.qmd
            text: Assignment 5
  


format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual


