project:
  type: website
  output-dir: .

website:
  title: ""

  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: project.qmd
        text: Project
      - href: cv.pdf
        text: CV
      - text: EPPS 6323
        menu:
          - href: assignment1.qmd
            text: Assignment 1
      - text: EPPS 6354
        menu:
        - href: assignment2.qmd
          text: assignment2
  


format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual


